### ISSUE TITLE
[Question] Whats the redis in this compose for?

### ISSUE THREAD

**Issue by OfficialLambdax** [GarretSidzaka/docker-conanexiles#4]
Title already says it. Whats the redis and redis insight in this compose for and why is it exposed to the internet by default?
```yaml
  redis:
    image: redis:5-alpine
    container_name: redis
    restart: unless-stopped
    environment:
      - "TZ=UTC"
    volumes:
      - redis:/data/
    ports:
      - 6379:6379
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: unless-stopped
    ports:
      - 8001:8001
    volumes:
      - insight:/db
```
